CREATE DATABASE if NOT EXISTS papyrus;
USE papyrus; 

CREATE TABLE if NOT EXISTS vente(
DELLIV 	SMALLINT (5),
QTE1 		INT 		(10),
PRIX1 	VARCHAR 	(50),
QTE2 		INT 		(10),
PRIX2 	VARCHAR 	(50),
QTE3 		INT 		(10),
PRIX3 	VARCHAR 	(50),
NUMFOU 	VARCHAR 	(25),
CODART 	CHAR 		(4)
);

CREATE TABLE if NOT EXISTS produit(
CODART 	CHAR 		(4),
LIBART 	VARCHAR 	(30),
STKALE	INT 		(10),
STKPHY 	INT 		(10),
QTEANN 	INT 		(10),
UNIMES 	CHAR 		(5)
);

CREATE TABLE if NOT EXISTS ligcom (
NUMLIG 	TINYINT 	(3), 
QTECDE 	INT 		(10),
PRIUNI 	VARCHAR 	(50),
QTELIV 	INT 		(10),
DERVLIV 	DATETIME (6),
NUMCOM 	INT 		(10),
CODART 	CHAR 		(4),
PRIMARY KEY (NUMLIG)
);

CREATE TABLE if NOT EXISTS entcom (
NUMCOM 	INT 		(10),
OBSCOM 	VARCHAR 	(50),
DATCOM 	DATE 		(10),
NUMFOU 	VARCHAR (25)
);

CREATE TABLE if NOT EXISTS fournis(
NUMFOU 	VARCHAR (25),
NOMFOU 	VARCHAR (25),
RUEFOU 	VARCHAR (50),
POSFOU 	CHAR 	  (5),
VILFOU 	VARCHAR (30),
CONFOU 	VARCHAR (15),
SATISF 	TINYINT (3)
);

